const contactRouter = require('./contact')
const shopRouter = require('./shop')
const cartRouter = require('./cart')
const loginRouter = require('./login')
const signupRouter = require('./signup')
const bodyparser = require('body-parser')
const newsRouter = require('./news')
const adminRouter = require('./admin')
const generalTablesRouter = require('./generalTables')
const insertUserRouter = require('./insertUser')
const deleteUserRouter = require('./deleteUser')
const updateUserRouter = require('./updateUser')
// const insertProductRouter = require('./insertProduct')
// const deleteProductRouter = require('./deleteProduct')
// const updateProductRouter = require('./updateProduct')
var unrlencodeParser = bodyparser.urlencoded({extended: false})
function route(app){
    app.use('/contact',unrlencodeParser, contactRouter)
    app.use('/shop', unrlencodeParser, shopRouter)
    app.use('/cart',unrlencodeParser, cartRouter)
    app.use('/login',unrlencodeParser, loginRouter)
    app.use('/signup', unrlencodeParser, signupRouter)
    app.use('/news',unrlencodeParser, newsRouter)
    app.use('/admin',unrlencodeParser, adminRouter)
    app.use('/generalTables', unrlencodeParser, generalTablesRouter)
    app.use('/insertUser',unrlencodeParser, insertUserRouter)
    app.use('/deleteUser',unrlencodeParser, deleteUserRouter)
    app.use('/updateUser',unrlencodeParser, updateUserRouter)
    // app.use('/insertProduct',unrlencodeParser, insertProductRouter)
    // app.use('/deleteProduct',unrlencodeParser, deleteProductRouter)
    // app.use('/updateProduct',unrlencodeParser, updateProductRouter)
    app.get('/', (req, res) =>  res.render('home'))
}

module.exports = route